package upgraders

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// ResourceManagementServiceGtpV0 is the V0 schema where multiple fields were TypeMap.
func ResourceManagementServiceGtpV0() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{
			"name": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Object name.",
			},
			"version": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "GTP version.",
				Default:     "V2",
			},
			"access_point_name": {
				Type:        schema.TypeMap,
				Optional:    true,
				Description: "Match by Access Point Name.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"enable": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "",
							Default:     false,
						},
						"apn": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "The Access Point Name object identified by Name or UID.",
						},
					},
				},
			},
			"allow_usage_of_static_ip": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "Allow usage of static IP addresses.",
				Default:     true,
			},
			"apply_access_policy_on_user_traffic": {
				Type:        schema.TypeMap,
				Optional:    true,
				Description: "Apply Access Policy on user traffic.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"enable": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "",
							Default:     false,
						},
						"add_imsi_field_to_log": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "Add IMSI field to logs generated by user traffic.",
							Default:     false,
						},
					},
				},
			},
			"cs_fallback_and_srvcc": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "CS Fallback and SRVCC (Relevant for V2 only).",
				Default:     true,
			},
			"imsi_prefix": {
				Type:        schema.TypeMap,
				Optional:    true,
				Description: "Match by IMSI prefix.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"enable": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "",
							Default:     false,
						},
						"prefix": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "The IMSI prefix.",
						},
					},
				},
			},
			"interface_profile": {
				Type:        schema.TypeMap,
				Optional:    true,
				Description: "Match only message types relevant to the given GTP interface. Relevant only for GTP V1 or V2.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"profile": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "The Interface Profile object identified by Name or UID.",
							Default:     "Any",
						},
						"custom_message_types": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "The messages types to match on them for this service. To specify a range, add a hyphen between the lowest and the highest numbers, for example: 32-35. Multiple Ranges can be chosen when separated with comma. This field relevant only when the Interface profile is set to 'Custom'.",
						},
					},
				},
			},
			"ldap_group": {
				Type:        schema.TypeMap,
				Optional:    true,
				Description: "Match by an LDAP Group.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"enable": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "",
							Default:     false,
						},
						"group": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "The Ldap Group object identified by Name or UID.",
						},
						"according_to": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "According to MS-ISDN or according to IMSI.",
							Default:     "MS-ISDN",
						},
					},
				},
			},
			"ms_isdn": {
				Type:        schema.TypeMap,
				Optional:    true,
				Description: "Match by an MS-ISDN.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"enable": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "",
							Default:     false,
						},
						"ms_isdn": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "The MS-ISDN.",
						},
					},
				},
			},
			"radio_access_technology": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "Match by Radio Access Technology.",
				MaxItems:    1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"utran": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "(1).",
							Default:     false,
						},
						"geran": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "(2).",
							Default:     false,
						},
						"wlan": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "(3).",
							Default:     false,
						},
						"gan": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "(4).",
							Default:     false,
						},
						"hspa_evolution": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "(5).",
							Default:     false,
						},
						"eutran": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "(6).",
							Default:     false,
						},
						"virtual": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "(7).",
							Default:     false,
						},
						"nb_iot": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "(8).",
							Default:     false,
						},
						"other_types_range": {
							Type:        schema.TypeList,
							Optional:    true,
							Description: "(9-255).",
							MaxItems:    1,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"enable": {
										Type:        schema.TypeBool,
										Optional:    true,
										Description: "",
										Default:     false,
									},
									"types": {
										Type:        schema.TypeString,
										Optional:    true,
										Description: "Other RAT Types. To specify other RAT ranges, add a hyphen between the lowest and the highest numbers, for example: 11-15. Multiple Ranges can be chosen when separated with comma.",
									},
								},
							},
						},
					},
				},
			},
			"restoration_and_recovery": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "Restoration and Recovery (Relevant for V2 only).",
				Default:     true,
			},
			"reverse_service": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "Accept PDUs from the GGSN/PGW to the SGSN/SGW on a previously established PDP context, even if different ports are used.",
				Default:     false,
			},
			"selection_mode": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "Match by a selection mode.",
				MaxItems:    1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"enable": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "",
							Default:     false,
						},
						"mode": {
							Type:        schema.TypeInt,
							Optional:    true,
							Description: "The mode as integer. [0 - Verified, 1 - MS - Not verified, 2 - Network - Not verified].",
						},
					},
				},
			},
			"trace_management": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "Trace Management (Relevant for V2 only).",
				Default:     true,
			},
			"tags": {
				Type:        schema.TypeSet,
				Optional:    true,
				Description: "Collection of tag identifiers.",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
			"color": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Color of the object. Should be one of existing colors.",
				Default:     "black",
			},
			"comments": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Comments string.",
			},
			"groups": {
				Type:        schema.TypeSet,
				Optional:    true,
				Description: "Collection of group identifiers.",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
			"ignore_warnings": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "Apply changes ignoring warnings.",
				Default:     false,
			},
			"ignore_errors": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "Apply changes ignoring errors. You won't be able to publish such a changes. If ignore-warnings flag was omitted - warnings will also be ignored.",
				Default:     false,
			},
		},
	}
}

// ResourceManagementServiceGtpStateUpgradeV0 converts the TypeMap fields to TypeList.
func ResourceManagementServiceGtpStateUpgradeV0(_ context.Context, rawState map[string]interface{}, _ interface{}) (map[string]interface{}, error) {
	return UpgradeMapsToLists(rawState,
		"access_point_name", "apply_access_policy_on_user_traffic",
		"imsi_prefix", "interface_profile", "ldap_group", "ms_isdn",
	), nil
}
